package currency;

public class CBRCurrencyCodesProvider {

    public static String getCurrencyCBRCode(String currency) {
        switch (currency.toUpperCase()) {
            case "AUD":
                return "R01010";
            case "ATS":
                return "R01015";
            case "AZN":
                return "R01020A";
            case "GBP":
                return "R01035";
            case "AON":
                return "R01040F";
            case "AMD":
                return "R01060";
            case "BYN":
                return "R01090B";
            case "BEF":
                return "R01095";
            case "BGN":
                return "R01100";
            case "BRL":
                return "R01115";
            case "HUF":
                return "R01135";
            case "HKD":
                return "R01200";
            case "GRD":
                return "R01205";
            case "DKK":
                return "R01215";
            case "USD":
                return "R01235";
            case "EUR":
                return "R01239";
            case "INR":
                return "R01270";
            case "IEP":
                return "R01305";
            case "ISK":
                return "R01310";
            case "ESP":
                return "R01315";
            case "ITL":
                return "R01325";
            case "KZT":
                return "R01335";
            case "CAD":
                return "R01350";
            case "KGS":
                return "R01370";
            case "CNY":
                return "R01375";
            case "KWD":
                return "R01390";
            case "LVL":
                return "R01405";
            case "LBP":
                return "R01420";
            case "LTL":
                return "R01435";
            case "MDL":
                return "R01500";
            case "DEM":
                return "R01510";
            case "NLG":
                return "R01523";
            case "NOK":
                return "R01535";
            case "PLN":
                return "R01565";
            case "PTE":
                return "R01570";
            case "ROL":
                return "R01585";
            case "RON":
                return "R01585F";
            case "SGD":
                return "R01625";
            case "SRD":
                return "R01665A";
            case "TJS":
                return "R01670";
            case "TJR":
                return "R01670B";
            case "TRY":
                return "R01700J";
            case "TMM":
                return "R01710";
            case "TMT":
                return "R01710A";
            case "UZS":
                return "R01717";
            case "UAH":
                return "R01720";
            case "FIM":
                return "R01740";
            case "FRF":
                return "R01750";
            case "CZK":
                return "R01760";
            case "SEK":
                return "R01770";
            case "CHF":
                return "R01775";
            case "EEK":
                return "R01795";
            case "YUN":
                return "R01805";
            case "ZAR":
                return "R01810";
            case "KRW":
                return "R01815";
            case "JPY":
                return "R01820";
        }
        return "";
    }
}
